// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQ3J4MSWD6tyhLp7IVXT7BI3wVUojj7A',
    appId: '1:1066513788354:web:db6a58b485a5b01831fa5b',
    messagingSenderId: '1066513788354',
    projectId: 'chattrail-5df9f',
    authDomain: 'chattrail-5df9f.firebaseapp.com',
    storageBucket: 'chattrail-5df9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrcy_nFTnN6N6pMONdKKZaKcJQPHAO0yM',
    appId: '1:1066513788354:android:83081259fc57e48931fa5b',
    messagingSenderId: '1066513788354',
    projectId: 'chattrail-5df9f',
    storageBucket: 'chattrail-5df9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByui8kUZnsAda5l82uBTDrQU61IGK4Kxo',
    appId: '1:1066513788354:ios:14beaf8c91898afc31fa5b',
    messagingSenderId: '1066513788354',
    projectId: 'chattrail-5df9f',
    storageBucket: 'chattrail-5df9f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
